export const doctors = [
  {
    id: 1,
    name: "Dr. Pranendra Singh",
    designation: "Medical Director & Chief Surgeon",
    experience: "15+",
    procedures: "5,000+",
    rating: "4.9",
    successRate: "95%+",
    location: "Delhi",
    languages: ["Hindi", "English", "Punjabi"],
    image: "/uploads/turkey-doctor.jpg",
    specialtyBadge: "Turkey FUE Director",
    about:
      "Founder of Ryan Clinic and India's foremost authority on Turkey's Sapphire FUE technique. Trained directly under Turkey's leading specialists in Istanbul. With 15+ years and 5,000+ procedures, Dr. Singh is the reason Ryan Clinic is India's only clinic certified to perform authentic Sapphire FUE with the original Choi Pen.",
    qualifications: [
      { degree: "MBBS", institute: "AIIMS, New Delhi" },
      { degree: "MS – General Surgery", institute: "PGIMER, Chandigarh" },
      { degree: "Fellowship – Hair Restoration", institute: "Istanbul, Turkey" },
    ],
    specializations: ["Turkey Sapphire FUE", Turkish Technique Choi Pen", "Hairline Design", "Crown Restoration", "High-Density FUE"],
    certifications: [
      "Turkey Sapphire FUE Certification — Istanbul Hair Institute",
      "NABH-Certified Operating Surgeon",
      "ISHRS Member — International Society of Hair Restoration Surgery",
      "Best Hair Transplant Surgeon — India 2022 & 2023",
    ],
    achievements: [
      "Featured in Times of India, NDTV Health, Hindustan Times",
      "200+ NRI patients from UK, USA, UAE & Australia",
      "Trained under Dr. Koray Erdogan — Turkey's #1 specialist",
    ],
  },
  {
    id: 2,
    name: "Dr. Arvind Mehta",
    designation: "Senior Hair Transplant Surgeon",
    experience: "12+",
    procedures: "3,500+",
    rating: "4.8",
    successRate: "92%+",
    location: "Mumbai",
    languages: ["Hindi", "English", "Marathi"],
    image: "/uploads/turkey-1.jpeg",
    specialtyBadge: "DNB Plastic Surgeon",
    about:
      "Leads Ryan Clinic's Mumbai branch with 12+ years of surgical precision. A DNB-certified plastic surgeon and Turkey FUE specialist, Dr. Mehta is sought after for complex beard, eyebrow, and full-scalp crown restorations. Rated 4.8★ across 800+ verified Google reviews.",
    qualifications: [
      { degree: "MBBS", institute: "KEM Hospital, Mumbai" },
      { degree: "DNB – Plastic Surgery", institute: "National Board of Examinations" },
      { degree: "Turkey-Certified FUE Specialist", institute: "Istanbul, Turkey" },
    ],
    specializations: ["Sapphire FUE", "Beard Transplant", "Eyebrow Restoration", "Crown Restoration"],
    certifications: [
      "DNB Plastic Surgery — National Board of Examinations",
      "Turkey FUE Certification — Istanbul Hair Institute",
      "NABH-Certified Operating Surgeon",
    ],
    achievements: [
      "3,500+ successful procedures across Mumbai branch",
      "Specialist in complex multi-session crown restorations",
      "Rated #1 hair transplant surgeon in Andheri, Mumbai",
    ],
  },
  {
    id: 3,
    name: "Dr. Priya Kapoor",
    designation: "Trichologist & Dermatologist",
    experience: "10+",
    procedures: "2,800+",
    rating: "4.9",
    successRate: "N/A",
    location: "Hyderabad",
    languages: ["Hindi", "English", "Telugu"],
    image: "/uploads/about-one.jpg",
    specialtyBadge: "IAT Trichologist",
    about:
      "Ryan Clinic's lead dermatologist and trichologist at the Hyderabad branch. With an MD in Dermatology and an IAT Fellowship in Trichology, Dr. Kapoor specialises in diagnosing root causes of hair loss — particularly in women. Hyderabad's most sought-after specialist for female pattern hair loss and PRP therapy.",
    qualifications: [
      { degree: "MBBS", institute: "Osmania Medical College, Hyderabad" },
      { degree: "MD – Dermatology", institute: "Nizam's Institute of Medical Sciences" },
      { degree: "Fellowship – Trichology (IAT)", institute: "International Association of Trichologists" },
    ],
    specializations: ["Female Pattern Hair Loss", "PRP Therapy", "LLLT Laser Therapy", "Scalp Diagnosis", "Alopecia Treatment"],
    certifications: [
      "MD Dermatology — NMC Recognised",
      "Trichology Fellowship — IAT Certified",
      "PRP & Regenerative Medicine Certification",
    ],
    achievements: [
      "India's leading female pattern hair loss specialist",
      "2,800+ PRP and non-surgical sessions completed",
      "Published research on female alopecia in peer-reviewed journals",
    ],
  },
  {
    id: 4,
    name: "Dr. Rohit Verma",
    designation: "Hair Restoration & Hairline Specialist",
    experience: "8+",
    procedures: "1,800+",
    rating: "4.8",
    successRate: "91%+",
    location: "Delhi",
    languages: ["Hindi", "English"],
    image: "/uploads/turkey-2.jpeg",
    specialtyBadge: "Hairline Artistry",
    about:
      "Ryan Clinic's hairline artistry specialist — combining surgical precision with a trained eye for natural aesthetics. His dual expertise in restoration surgery and trichology means he handles both the procedure and long-term hair health. Trusted for hairlines so natural they're completely undetectable, even to barbers.",
    qualifications: [
      { degree: "MBBS", institute: "Maulana Azad Medical College, Delhi" },
      { degree: "MS – General Surgery", institute: "University of Delhi" },
      { degree: "Diploma – Trichology", institute: "IAT Certified Programme" },
    ],
    specializations: ["Natural Hairline Design", "FUE Hair Transplant", "FUE + PRP Combo", "Temple & Frontal Restoration"],
    certifications: [
      "MS General Surgery — NMC Recognised",
      "IAT Trichology Diploma",
      "Hairline Design & Artistry Certification",
    ],
    achievements: [
      "Known for 'undetectable' hairlines — featured in lifestyle media",
      "1,800+ procedures with zero reported complications",
      "Preferred surgeon for stage actors and media professionals",
    ],
  },
];
